### PR TITLE
willBeginDragging and didEndDecelerating closures

### PR DESCRIPTION
**Pull request by El-Fitz**
Added two closures to expose the ScrollView's willBeginDragging and didEndDecelerating methods
ReadMe updated accordingly

### CODE REVIEW

**Comment by El-Fitz** [comment]
What went wrong ?

**Comment by zvonicek** [comment]
Thanks for the PR! Could you please fix line indention so you use 4 spaces (as elsewhere in the project) and update your branch from master so there are no merge conflicts? Thanks!

**Comment by El-Fitz** [comment]
Will do this this week-end :-)

**Comment by El-Fitz** [comment]
I think it's good. Not sure (I'm still learning git)

**Comment by El-Fitz** [comment]
Ok, seems like I didn't get it.
What should I do, exactly ?

**Pull request merged**
