### PR TITLE
[SPM] Fix:  Showing All Messages found `X` file(s) which are unhandled; explicitly declare them as resources or exclude from the target

### PR DESCRIPTION
**Pull request by dogo**
Screen Shot 2021-09-21 at 23 58 30

### CODE REVIEW

**Comment by MadGeorge** [comment]
@zvonicek, please review, merge and release a new version with this fix. It's Very annoying to observe warnings in the Xcode project just from one dependency. 

Thanks for the library, by the way.

**Comment by Kondamon** [comment]
@dogo Your commit doesn't resolve the issue. You need to add these excludes for the ImageSlideShow target:

```
...
targets: [
        .target(
            name: "ImageSlideshow",
            path: "ImageSlideshow",
            exclude: ["Classes/InputSources/AFURLSource.swift",
                      "Classes/InputSources/AlamofireSource.swift",
                      "Classes/InputSources/AlamofireLegacySource.swift",
                      "Classes/InputSources/ParseSource.swift",
                      "Classes/InputSources/KingfisherSource.swift",
                      "Classes/InputSources/SDWebImageSource.swift"],
            sources: [
                "Classes/Core/ActivityIndicator.swift",
                "Classes/Core/Bundle+Module.swift",
                "Classes/Core/FullScreenSlideshowViewController.swift",
                "Classes/Core/ImageSlideshow.swift",
                "Classes/Core/ImageSlideshowItem.swift",
                "Classes/Core/InputSource.swift",
                "Classes/Core/PageIndicator.swift",
                "Classes/Core/PageIndicatorPosition.swift",
                "Classes/Core/SwiftSupport.swift",
                "Classes/Core/UIImage+AspectFit.swift",
                "Classes/Core/UIImageView+Tools.swift",
                "Classes/Core/ZoomAnimatedTransitioning.swift",
            ],
            resources: [
                .copy("Assets/ic_cross_white@2x.png"),
                .copy("Assets/ic_cross_white@3x.png"),
            ]),
...
```

**Review by Kondamon — CHANGES_REQUESTED** [review]
Add exclude files for "ImageSlideshow" target

**Comment by odanu** [comment]
@zvonicek Hey hey, is this anyhow going to be merged soon?

**Comment by dogo** [comment]
Any news @zvonicek  ?

**Comment by vickygaugau** [comment]
Hi all
I am using this library and i dont know way how to use these feature configure
- slideshowInterval - slideshow interval in seconds (default 0 – disabled)
- zoomEnabled - enables zooming (default false)
- circular - enables circular scrolling (default true)
Can you help me?
Thanks all
@zvonicek Thank you so much

**Pull request closed without merging**
