### PR TITLE
Caption Support

### PR DESCRIPTION
**Pull request by benwalch**

### CODE REVIEW

**Comment by Riichie** [comment]
+1

**Comment by jaimeagudo** [comment]
Any feedback on this? :)

**Comment by dogo** [comment]
Ping @zvonicek

**Comment by Haojen** [comment]
hi, @zvonicek 

thank you write the library, i love it 😃 

but now , i wanna add caption to every each photos,  so i come here, and i don't know how to add caption to eacth photos, i hope if you got time tell me how to do .

thank you again, sorry about my english .

**Pull request closed without merging**
