### PR TITLE
RTL support

### PR DESCRIPTION
**Pull request by bohachevskyy**

### CODE REVIEW

**Comment by bohachevskyy** [comment]
Hello @almatri this PR hasn't been merged. RTL support is still missing in this library. You can use ImageSlideshow forked by me.

**Comment by zvonicek** [comment]
Hi @bohachevskyy! Thanks for the PR and sorry for my late response. I'd like to merge the PR, but I noticed that the transformation you do make the image in full screen upside down. Do you have an idea how to fix it?

simulator screen shot - iphone se - 2019-01-13 at 16 01 04

**Comment by noura-rizk** [comment]
Hi, Thanks for the PR, I'm also having the same issue with the image it transforms upside down, can you help please, thanks.

**Comment by bojanb89pa** [comment]
Hi @noura-rizk, I think you should check if RTL is set with function: `UIView.userInterfaceLayoutDirection(for: myView.semanticContentAttribute)`
instead of checking `lang == "ar"`

**Comment by noura-rizk** [comment]
> Hi @noura-rizk, I think you should check if RTL is set with function: `UIView.userInterfaceLayoutDirection(for: customView) == .rightToLeft`
> instead of checking `lang == "ar"`

I did that at first but had some issues when changing language inside the app so that was a quick fix I'll post another clean code when I've time

**Comment by bohachevskyy** [comment]
Hey @zvonicek thank you for you review. It may depends on language as @noura-rizk said, need to investigate this issue.

@noura-rizk FYI: it's not only Arabic language is right to left. There are 4-5 of them.

**Comment by bohachevskyy** [comment]
Hey, @zvonicek. Sorry for my late response. I tried on different simulators with different local. Didn't manage to reproduce it. Could you provide more details about the simulator that you used, please?

image

**Comment by zvonicek** [comment]
Hi @bohachevskyy, thanks for your response, now I'm late with mine 😄 
I can reproduce the issue by setting "Right-to-Left Pseudolanguage" as Application Language in my scheme on iPhone XR, 12.1 (but it shouldn't hopefully matter).

Screenshot 2019-04-14 at 13 01 15

**Comment by kmatskevich** [comment]
Hey, guys. Please, apply these changes to the repo.
@zvonicek

**Pull request merged**
