### PR TITLE
Support Swift Package Manager

### PR DESCRIPTION
**Pull request by Nixon506E**

### CODE REVIEW

**Comment by zvonicek** [comment]
Thanks for the PR. I checked your solution and it has a flaw that dependencies to Parse, Kingfisher, SDWebImage, Alamofire and Alamofire are added for everyone, regardless if they want to use for example just Alamofire.

**Comment by Nixon506E** [comment]
I think all of the dependencies get loaded into an Xcode cache but only the libraries that are selected are then loaded into the target.

**Comment by pcmanik** [comment]
@zvonicek yes it should work like @Nixon506E is saying. So only frameworks for selected targets are bundled into app binary. So in case of target **ImageSlideshow** nothing other than library itself will be bundled.

Please can you merge this pull request and release new version? I would like to migrate from Carthage and also test macCatalyst in my app.

Thank you.

**Comment by zvonicek** [comment]
I just pushed the support for SPM to master. Thanks for the contribution!

**Pull request closed without merging**
